CREATE SCHEMA `auth` DEFAULT CHARACTER SET utf8mb4 ;

CREATE TABLE `db`.`GROUP` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `DESCRIPTION_UNIQUE` (`DESCRIPTION` ASC) VISIBLE);


CREATE TABLE `db`.`USER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(45) NULL,
  `LAST_NAME` VARCHAR(45) NULL,
  `ID_GROUP` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `user-group_idx` (`ID_GROUP` ASC) VISIBLE,
  CONSTRAINT `user-group`
    FOREIGN KEY (`ID_GROUP`)
    REFERENCES `db`.`GROUP` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);